"""
Runtime env config IO (runtime_meta format) for MAPF Agent.

Format is aligned with `mapf_agent/knowledge/env_runtime_config.md`:
{
  "meta": {...},
  "config": {
    "sim": {...},       # subset/override of config.settings.SimConfig
    "fault": {...},     # optional subset/override of FaultConfig
    "order_modes": {...}  # optional mode-specific configs
  }
}
"""

from __future__ import annotations

import json
import os
import time
from dataclasses import fields as dataclass_fields
from typing import Any, Dict, Optional

from config.settings import FaultConfig, SimConfig
from mapf_agent.tools.runtime_config import load_runtime_config


def _project_dirs() -> Dict[str, str]:
    from mapf_agent.config import PROJECT_ROOT

    env_runtime_dir = os.path.join(PROJECT_ROOT, "config", "envs", "runtime")
    env_fallback_dir = os.path.join(PROJECT_ROOT, "config", "envs")
    return {"env_runtime_dir": env_runtime_dir, "env_fallback_dir": env_fallback_dir}


def _ensure_dir(path: str) -> None:
    os.makedirs(path, exist_ok=True)


def build_runtime_meta_payload(map_file: str, sim_overrides: Dict[str, Any]) -> Dict[str, Any]:
    """
    Build runtime_meta payload containing:
    - config.sim: always includes map_file + provided sim_overrides
    - fault and order_modes: left empty for conciseness (defaults will apply)
    """
    from config.settings import OrderMode

    sim_field_names = {f.name for f in dataclass_fields(SimConfig)}
    fault_field_names = {f.name for f in dataclass_fields(FaultConfig)}

    payload: Dict[str, Any] = {
        "meta": {
            "version": 1,
            "description": "generated by mapf_agent",
            "created_at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
            "created_by": "mapf_agent",
        },
        "config": {
            "sim": {"map_file": map_file},
            "fault": {},
            "order_modes": {m.value: {} for m in OrderMode},
        },
    }

    # Insert validated overrides (already validated by sim_config_validator).
    # `sim_overrides` may include both SimConfig and FaultConfig keys
    # because the current parser puts them into the same object.
    for k, v in (sim_overrides or {}).items():
        if k in sim_field_names:
            payload["config"]["sim"][k] = v
        elif k in fault_field_names:
            payload["config"]["fault"][k] = v
        # else: ignore (should not happen after validation)
    return payload


def save_env_runtime_meta_json(payload: Dict[str, Any], out_path: Optional[str] = None) -> str:
    """
    Save payload to `config/envs/runtime/` (fallback to config/envs/) and return path.
    """
    dirs = _project_dirs()
    base_dir = dirs["env_runtime_dir"]
    fallback_dir = dirs["env_fallback_dir"]

    if out_path is None:
        ts = time.strftime("%Y%m%d_%H%M%S", time.localtime())
        name = f"env_runtime_{ts}.json"
        out_path = os.path.join(base_dir, name)
    else:
        out_path = str(out_path)

    # Ensure directory exists; if runtime dir missing and cannot create, fallback.
    try:
        _ensure_dir(os.path.dirname(out_path) or ".")
    except Exception:
        ts = time.strftime("%Y%m%d_%H%M%S", time.localtime())
        out_path = os.path.join(fallback_dir, f"env_runtime_{ts}.json")
        _ensure_dir(fallback_dir)

    with open(out_path, "w", encoding="utf-8") as f:
        json.dump(payload, f, indent=2, ensure_ascii=False)

    return out_path


def update_env_runtime_meta_sim(env_runtime_json_path: str, sim_updates: Dict[str, Any]) -> None:
    """Update config.sim fields inside an existing runtime_meta JSON."""
    if not env_runtime_json_path or not os.path.isfile(env_runtime_json_path):
        return
    if not sim_updates:
        return

    with open(env_runtime_json_path, "r", encoding="utf-8") as f:
        data = json.load(f)

    config = data.get("config") or {}
    sim = config.get("sim") or {}
    sim.update(sim_updates)
    config["sim"] = sim
    data["config"] = config

    with open(env_runtime_json_path, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)


def _apply_to_dataclass_class(dataclass_instance: Any, dataclass_cls: Any) -> Dict[str, Any]:
    applied: Dict[str, Any] = {}
    for f in dataclass_fields(dataclass_cls):
        v = getattr(dataclass_instance, f.name)
        setattr(dataclass_cls, f.name, v)
        applied[f.name] = v
    return applied


def apply_runtime_meta_to_sim_classes(env_runtime_json_path: str) -> Dict[str, Any]:
    """
    Load runtime_meta JSON and apply it to in-memory config classes:
    - SimConfig
    - FaultConfig
    - order mode dataclasses (ContinuousConstantConfig, etc.)
    """
    runtime = load_runtime_config(env_runtime_json_path)

    applied: Dict[str, Any] = {}

    # SimConfig
    applied["sim"] = {}
    for f in dataclass_fields(SimConfig):
        v = getattr(runtime.sim, f.name)
        setattr(SimConfig, f.name, v)
        applied["sim"][f.name] = v

    # FaultConfig
    applied["fault"] = {}
    for f in dataclass_fields(FaultConfig):
        v = getattr(runtime.fault, f.name)
        setattr(FaultConfig, f.name, v)
        applied["fault"][f.name] = v

    # Order-mode specific config dataclasses:
    # strategies reference these configs as class-level fields.
    applied["order_modes"] = {}
    for mode, cfg_instance in runtime.order_modes.items():
        cfg_cls = type(cfg_instance)
        applied["order_modes"][mode.value] = _apply_to_dataclass_class(cfg_instance, cfg_cls)

    return applied

